- hosts: all
  vars_files:
    - vars/path.yml
    - vars/shell.yml
    - vars/distribution_packages.yml
    - vars/brew_packages.yml
  environment:
    NONINTERACTIVE: 1
  tasks:
    - name: "Install default tools"
      block:
        - name: install packages
          include_tasks: tasks/packages.yml

        - name: set shell
          include_tasks: tasks/shell.yml

        - name: post install
          include_tasks: tasks/post_install.yml
