- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/github"
    type: ed25519
    comment: "{{ git_email }}"

- name: Set git config
  git_config:
    scope: global
    name: user.email
    value: "{{ git_email }}"

- name: Set git config
  git_config:
    scope: global
    name: user.name
    value: "{{ git_name }}"
